### ISSUE TITLE
Add to luscius 

### ISSUE THREAD

**Issue by HouseHouseHause1** [master7720/anarchy-skid-list#22]
He be a manipulator and a ped0, he got exposed by my friends in one of the best events lmao, you can come to my dms on discord if you want me to explain more: House 1#0873

**Comment by master7720** [comment]
can you add more info?

**Comment by HouseHouseHause1** [comment]
As I said, you can contact me for more on my discord as I have proofs there.

**Comment by master7720** [comment]
your discord doesnt work

**Comment by HouseHouseHause1** [comment]
House 1#6013 my new discord, my bad LOL.
